# Action to generate metrics using LowLighter/Metrics by Simon Lecoq

# All results are in SVG format, and commited to /assets/metrics/ in master branch.
# Split into multiple jobs, to prevent everything failing if one component errors,
# And to improve the loading and layout of /METRICS.md where the SVGs are displayed

name: 📊 Generates Metrics
on:
  schedule:
    - cron: '0 2 * * 0' # At 02:00 on Sunday
  workflow_dispatch: # Or when it's manually triggered
jobs:        
  # Sponsors Card
  sponsor-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/sponsors.svg
          committer_message: "📊 Updates metrics - sponsors"
          # Options
          user: nitai-satapathy
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 36
  
  # 10 Years worth of contribution charts
  historical-contribuitions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/contributions.svg
          committer_message: "📊 Updates metrics - contributions"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_calendar: yes
          plugin_calendar_limit: 3
  
  # Ticket (Issue + PR) Follow Ups
  ticket-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/tickets.svg
          committer_message: "📊 Updates metrics - tickets"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

  
  # Coding Habits
  coding-habits-metrics:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Coding Habits
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/habits.svg
          committer_message: "📊 Updates metrics - habbits"
          user: nitai-satapathy
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_days: 28
          plugin_habits_from: 500
          config_timezone: Europe/London
      - name: Upload Habits Artifact
        uses: actions/upload-artifact@v3
        with:
          name: habits-artifact
          path: assets/metrics/habits.svg

  # Total Stargazers
  stargazer-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/stargazers.svg
          committer_message: "📊 Updates metrics - stargazers"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 365

  # Recent Activity
  activity-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Activity
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/activity.svg
          committer_message: "📊 Updates metrics - activity"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 15
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, public
      - name: Upload Activity Artifact
        uses: actions/upload-artifact@v3
        with:
          name: activity-artifact
          path: assets/metrics/activity.svg

  # Reactions on comments / tickets
  reactions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/reactions.svg
          committer_message: "📊 Updates metrics - reactions"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 800
          plugin_reactions_limit_issues: 800
          plugin_reactions_limit_discussions: 800
          plugin_reactions_limit_discussions_comments: 800
          plugin_reactions_details: percentage, count


  # People who I follow / are following me
  people-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          committer_message: "📊 Updates metrics - people"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          filename: assets/metrics/people.svg
          user: nitai-satapathy
          base: ""
          plugin_people: yes
          plugin_people_types: followers, following
          

  # Languages that code is written in (probz just JS, yuck)
  language-metrics:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/languages.svg
          committer_message: "📊 Updates metrics - languages"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_recent_days: 120
          plugin_languages_other: yes
          plugin_languages_sections: most-used

  # Achievments, fake awards showing that i have no life
  acheiment-metrics:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Achievements
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/achievements.svg
          committer_message: "📊 Updates metrics - acheivments"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: detailed
      - name: Upload Achievements Artifact
        uses: actions/upload-artifact@v3
        with:
          name: achievements-artifact
          path: assets/metrics/achievements.svg

  # Notable contributions, if there are any lol
  notable-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/notable.svg
          committer_message: "📊 Updates metrics - notable contribs"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
      - name: Upload Notable Artifact
        uses: actions/upload-artifact@v3
        with:
          name: notable-artifact
          path: assets/metrics/notable.svg
 
  # Discussion metrics, i like to chat
  discussions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/discussions.svg
          committer_message: "📊 Updates metrics - discussions"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories_limit: 12
  
  # Gists, basically shit-code saved for later
  gists-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/gists.svg
          committer_message: "📊 Updates metrics - gists"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_gists: yes                 
   
  # Stars on projects i like
  starlists-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/starlists.svg
          committer_message: "📊 Updates metrics - starlists"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 12
          plugin_starlists_limit_repositories: 0
      - name: Upload Starlists Artifact
        uses: actions/upload-artifact@v3
        with:
          name: starlists-artifact
          path: assets/metrics/starlists.svg
          
  # Introduction, info from profile. Not that anyones interested
  intro-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/intro.svg
          committer_message: "📊 Updates metrics - intro"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_introduction: yes
      - name: Upload Intro Artifact
        uses: actions/upload-artifact@v3
        with:
          name: intro-artifact
          path: assets/metrics/intro.svg


  # Pinned Repositories
  repository-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/repositories.svg
          committer_message: "📊 Updates metrics - repositories"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: >-
            nitai-satapathy/2024-Olympics-Champion-Prediction, nitai-satapathy/Tennis_Game_Score_Tracker_in_C, nitai-satapathy/portfolio-1, nitai-satapathy/github-chapter-2-contributions
          
   
 # Starred Topics
  starred-topics-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/topics.svg
          committer_message: "📊 Updates metrics - topics"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: icons

  lines-code-changed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        filename: assets/metrics/lines-of-code.svg
        token:  ${{ secrets.BOT_GITHUB_TOKEN }}
        user: nitai-satapathy
        base: ""
        plugin_lines: yes
        plugin_lines_sections: repositories, history
        plugin_lines_repositories_limit: 2
        plugin_lines_history_limit: 1
        repositories_skipped: |
          @use.patterns
          */*
          +lowlighter/metrics
          
  # All Metrics together
  all-metrics:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate All
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/all.svg
          committer_message: "📊 Updates metrics - all"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          # Options
          user: nitai-satapathy
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
          plugin_traffic: yes
          plugin_gists: yes
          plugin_discussions: yes

  # Main Metrics - Short
  shorter-metrics:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate Shorter Summary
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          filename: assets/metrics/summary.svg
          committer_message: "📊 Updates metrics - summary"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: nitai-satapathy
          template: classic
          base: activity, community, repositories
          config_timezone: Europe/London
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_traffic: yes
          plugin_lines: yes
          plugin_discussions: yes
          plugin_discussions_categories: no
      - name: Upload Summary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: summary-artifact
          path: assets/metrics/summary.svg
