name: 👩‍💻 Inserts Recent Activity
on:
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Adds activity to readme
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          MAX_LINES: 10
      - name: Adds activity to file
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: ':zap: Updates recent activity'
        with:
          MAX_LINES: 100
          TARGET_FILE: './RECENT-ACTIVITY.md'
